name: deploy
on:
  push:
    branches:
      - test-deploy
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "17"
      - run: npm install
      - name: test
        run: echo 'test---'
      - name: start svr
        run: node server.js
